---
- hosts: pihole
  become: yes
  tasks:
    - name: Add the personal users
      user:
        name: "{{ personal_admin_user }}"
        password: "{{ personal_admin_password | password_hash('sha512') }}"
        comment: personal user for admin.
        groups: sudo
        append: yes
        update_password: on_create
    - name: Set authorized key for personal admin user copying it from current user.
      authorized_key:
        user: "{{ personal_admin_user }}"
        state: present
        #TODO: Update this to not assume the public key name
        key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
