# ansible-galaxy install -r requirements.yml to install the requirements on the ansible controller.

---
collections:
  # Install community.general for a number of things.
  - name: community.general

  # Install collection for hardening
  - name: devsec.hardening

  # My own personal collection.
  - name: https://github.com/nivintw/ansible-rpi-nivintw-baseline.git
    version: main
    type: git

  # For creating images / containers using podman
  - name: containers.podman
