# ansible-galaxy install -r requirements.yml to install the requirements on the ansible controller.

---
collections:
  # Install community.general for a number of things.
  - name: community.general

  # Install collection for hardening
  - name: devsec.hardening

roles:
  - name: geerlingguy.docker
  - name: geerlingguy.pip
