---
- name: Ansible Playbook for testing docker-container-pihole
  hosts: pihole
  roles:
    # - geerlingguy.pip
    - docker-container-pihole
  vars:
    pip_install_packages:
      - name:
          - docker
          - docker-compose

  # tasks:
  #   - name: Test Random Thing
  #   touch:

  remote_user: pi
  become: yes
