# Command to use to run the pihole container update (will update the base image and rebuild).
# ansible-playbook update-pihole-container-playbook.yml --ask-vault-pass

---
- name: Ansible Playbook for updating the pihole container image.
  hosts: pihole

  tasks:
    - include_role:
        name: docker-container-pihole
        tasks_from: update_pihole_base

  remote_user: pi
  become: yes
