---
- name: Reboot Pi
  ansible.builtin.shell: sleep 2 && reboot
  async: 1
  poll: 0
  tags:
    - pihole
  changed_when: false
  failed_when: false
  notify: Wait for Raspberry PI to come back

- name: Wait for Raspberry PI to come back
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    port: 22
    state: started
    delay: 10
  delegate_to: localhost
  become: false
