---
docker_pihole_container_name: pihole
docker_pihole_image_name: pihole-image

# docker_pihole_network: bridge
docker_pihole_network_interface: "{{ docker_pihole_network_interface }}"

# This is an example and should be over-ridden
docker_pihole_ipv4_address: 192.168.1.100
docker_pihole_purge_networks: true

# Specifying this option without a value will configure pihole
# to NOT have an admin password on the web interface.
# This is probably NOT what you want.
docker_pihole_admin_password:

docker_pihole_host_dir_dnsmasqd: /etc/dnsmasq.d/
docker_pihole_host_dir_pihole: /etc/pihole/
docker_pihole_volumes:
  - "{{ docker_pihole_host_dir_pihole }}:/etc/pihole/"
  - "{{ docker_pihole_host_dir_dnsmasqd }}:/etc/dnsmasq.d/"

# The timezone that pihole container will use
docker_pihole_timezone: "{{ all_personal_TZ }}"
# TODO: abstract this.
docker_pihole_domain: pihole.nivin.tech

docker_pihole_dns_custom_hosts: []
#  - name: somehost
#    ip: 192.168.1.123
#    aliases:
#      - beer
#      - pizza

docker_pihole_dns_custom_hosts_path: "{{ docker_pihole_host_dir_pihole }}custom_hosts.list"
docker_pihole_dns_custom_hosts_dnsmasq_conf_path: "{{ docker_pihole_host_dir_dnsmasqd }}99-custom-hosts.conf"

# Used to set what DNS the container will use.
# This does NOT set the upstream DNS servers for pihole.
# The address 127.0.0.1 tells the container to use itself for it's own DNS queries.
# For example, running `dig www.google.com` with the value 127.0.0.1 from inside the container should show
# that the container will not reach out to another external DNS provider.
# This is probably the value you want for configuring pihole.
docker_pihole_dns_servers:
  - "127.0.0.1"
