---
- name: Update /etc/hosts/ to reflect new hostname
  # I would have expected that the hostname directive would do this, but it does not.
  #! This is important! If /etc/hosts does not contain the right hostname sudo directives
  #! will be VERY slow.
  lineinfile:
    path: /etc/hosts
    regex: "^127\\.0\\.1\\.1.*"
    line: "127.0.1.1\tpihole"
    state: present
  tags:
    - adminPiHole

- name: "Setting hostname to {{ all_pihole_host_hostname }}"
  hostname:
    name: "{{ all_pihole_host_hostname }}"
  tags:
    - adminPiHole

- name: Disable Wifi - not needed on pihole
  shell: rfkill block wifi
  tags:
    - adminPiHole

- name: Disable Bluetooth - not needed on pihole
  shell: rfkill block bluetooth
  tags:
    - adminPiHole
# TODO: Is this next update section for the system?
# That file doesn't seem to exist. maybe remove.
# - name: Set PiHole to update every week
#   become: True
#   replace:
#     path: /etc/cron.d/pihole
#     regexp: "^#(.*updatePihole.*)$"
#     replace: '\1'
#     backup: yes
#   tags: admin
