# This tasks list includes optional tasks for configuring your pi and pihole to be
# accessible from multiple vlans.
# The actions here may be specific to Raspberry Pi OS.

---
- name: Install vlan package
  apt:
    name: vlan
    state: present
    # Assuming that this is ran at setup-time, the cache should be up-to-date.
    update_cache: false

  # Make sure this ran before adding vlan section.
- name: Configure static IP in /etc/dhcpcd.conf for untagged vlan
  become: yes
  lineinfile:
    dest: /etc/dhcpcd.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
    - {
        regexp: "^interface eth[0-9]$",
        line: "interface {{ docker_pihole_network_interface }}",
      }
    - {
        regexp: "^static ip_address",
        line: "static ip_address={{ docker_pihole_ipv4_address }}/24",
      }
    - { regexp: "^static routers", line: "static routers={{ lan_gateway }}" }

- name: Add vlan devices
  become: yes
  template:
    src: "etc_network_interfaces.d_vlans.j2"
    dest: /etc/network/interfaces.d/vlans

- name: Add vlan configurations
  become: yes
  blockinfile:
    dest: /etc/dhcpcd.conf
    block: "{{ lookup('template', 'etc_dhcpcd.conf.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR VLANS!"

  # TODO: find if there's a better way to restart network with ansible.
- name: Restart networking because of config changes
  become: yes
  shell: "systemctl restart networking"
