---
# This file contains tasks that configure a raspberry pi running Raspberry Pi OS.
# Nothing here is specific to pihole or docker or anything else.
# These tasks are just general configuration.

# Update these tasks with values that are relevant to your situation
# if they are different from the US-based defaults.
- name: Set timezone to local timezone as appropriate.
  community.general.timezone:
    name: "{{ all_personal_TZ }}"

- name: Set country for Wifi
  # Some systems I end up disabling the wifi, but it's still nice to set.
  shell: iw reg set US

- name: Install locale en_US.UTF-8
  community.general.locale_gen:
    name: en_US.UTF-8
    state: present

- name: Set locale en_US.UTF-8
  command: "update-locale LANG=en_US.UTF-8"
  register: locale

- name: Change keyboard to us-layout
  replace:
    destfile: /etc/default/keyboard
    regexp: '"gb"'
    replace: '"us"'
  ignore_errors: yes

- name: edit boot config to allow for HDMI hotplug
  #TODO: Also set default monitor res. to 1920x1080
  # This won't be the "right" answer for all monitors,
  # but will work for most and allow the hot-plug to not default to
  # a VERY low resolution that definitely doesn't look good on a 1920x1080 monitor.
  # To be clear: the below works as-is. The default resolution is just very low.
  blockinfile:
    path: /boot/config.txt
    block: |
      hdmi_force_hotplug=1
  tags:
    - piAdmin

- name: Add the personal user for administration
  user:
    name: "{{ personal_admin_user }}"
    password: "{{ personal_admin_password | password_hash('sha512') }}"
    comment: personal user for admin.
    groups: sudo
    append: yes
    update_password: on_create

- name: Set authorized key for personal admin user copying it from current user.
  authorized_key:
    user: "{{ personal_admin_user }}"
    state: present
    #TODO: Update this to not assume the public key name
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"

- name: Change default password for pi
  user:
    name: pi
    #* Note: Right now, I think this is always changing the password.
    # This might seem obvious looking at it, but reading the docs I thought it'd only change the password
    # if the password was different from the currently set password.
    #TODO: Check the above...
    password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits,punctuation') | password_hash('sha512')  }}"
    update_password: always

- name: Update APT package cache
  apt:
    update_cache: yes
  tags:
    - admin
    - software

- name: "Upgrade APT to the lastest packages"
  apt:
    upgrade: safe
  tags:
    - admin
    - software

- name: Install enhanced editor
  apt:
    name: vim
    state: present
    update_cache: false
  tags:
    - admin
    - software

- name: Install process observation tools
  apt:
    name: htop
    state: present
    update_cache: false
  tags:
    - admin
    - software

- name: Install cron job scheduler
  apt:
    name: cron
    state: present
    update_cache: false
  tags:
    - admin
    - software

# NOTE: Look at the aliases and decide if you want to edit or remove any of them.
# They seem fine to me and came from another open source project so I left them.
- name: "Set default bash aliases"
  copy: src=./files/etc_profile.d_bash_aliases.sh dest=/etc/profile.d/bash_aliases.sh mode=0600
  tags:
    - admin

- name: Install admin tools (python, nmap)
  apt:
    package:
      - python-apt
      - python-pip
      - nmap
    state: present
  tags:
    - admin
    - software
# - name: Install grin (better grep)
#   shell: pip install grin
#   tags: admin

# - name: Set static IP configuration
#   become: True
#   template: src="etc_network_interfaces.j2"
#     dest="/etc/network/interfaces"
#     owner=root
#     group=root
#     mode=0644
#   tags:
#     - pihole

- name: "Reboot"
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true
  tags:
    - admin

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ ansible_host }} port=22 state=started delay=10
  become: false
