---
- name: "[OCI / Podman] Build pihole image with unbound added"
  become: true
  containers.podman.podman_image:
    path: "/tmp/pihole_unbound"
    # NOTE: force the image to be built, even if it already exist.
    # Only useful while developing the ansible project itself.
    pull: false
    state: build
    force: true # temporary
    name: "{{ oci_pihole_image_name }}"

- name: "[OCI / Podman] Setup the pi-hole OCI container"
  become: true
  containers.podman.podman_container:
    image: "{{ oci_pihole_image_name }}"
    name: "{{ oci_pihole_container_name }}"
    recreate: true
    restart_policy: on-failure:3
    # state: quadlet should (ideally) ensure the container is always running under
    # systemd, even after e.g. a power failure / reboot.
    state: quadlet
    volumes: "{{ oci_container_pihole_volumes }}"
    env:
      TZ: "{{ docker_pihole_timezone }}"
      WEBPASSWORD: "{{ __docker_pihole_admin_password }}"
      # Use our unbound recursive DNS server as the upstream.
      # The semicolon at the end ensures that the recursive unbound server
      # is the ONLY upstream. Without it the pihole image sets a backup default upstream DNS server.
      PIHOLE_DNS_: 127.0.0.1#5335;
      # Make re-directing from / to /admin work automatically
      # by setting VIRTUAL_HOST to e.g. pihole.mydomain.tld
      VIRTUAL_HOST: "{{ pihole_domain_name }}"
    # This sets the DNS servers for the container, but not the upstream DNS providers for pihole.
    dns_servers: "{{ docker_pihole_dns_servers }}"
    published_ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "53:53/udp"
      - "53:53/tcp"
      - "67:67/udp"
    quadlet_options:
      # The below ensures that the container starts at boot.
      # Without this, the quadlet will be generated, but the container will not
      # be started at boot.
      - |
        [Install]
        WantedBy=default.target

- name: Setup custom hosts
  ansible.builtin.include_tasks: custom_hosts.yml
  when: docker_pihole_dns_custom_hosts | length > 0
