---
- name: "Set the __pihole_service_admin_password fact"
  ansible.builtin.set_fact:
    __pihole_service_random_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits') }}"
    __pihole_service_admin_password: "{{ pihole_service_admin_password | default(__pihole_service_random_password) }}"

- name: "Install Podman on Debian"
  ansible.builtin.import_tasks: install_podman.yml
  when: ansible_facts["os_family"] == "Debian"

- name: Copy Container Image Build Files to host for building.
  ansible.builtin.copy:
    src: pihole_unbound
    dest: /tmp
    force: true
    mode: "0644"

- name: "Build and create pihole unbound container"
  ansible.builtin.import_tasks: init_pihole_unbound_container.yml
  when: ansible_facts["os_family"] == "Debian"
